name: "Archetect Render Action"
description: "GitHub Action to render using Archetect https://github.com/archetect/archetect"
inputs:
  archetect-version:
    description: The Archetect version (https://github.com/archetect/archetect/releases)
    required: false
    default: "v0.6.1"
  archetect-os:
    description: The OS for the compiled Archetect binary [linux-x64, windows-x64, osx-x64]
    required: false
    default: "linux-x64"
  source:
    description: The source directory or Git repo containing an archetype.yml
    required: true
  destination:
    description: The destination of the rendered output
    required: false
    default: "." 
  options:
    description: Additional command-line options for the archetect command (e.g. -a, -A, -s)
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - id: install-binary
      run: |
        set -x
        echo "Downloading Archetect from GitHub..."
        pushd "${{ runner.temp }}"
        curl -LO "https://github.com/archetect/archetect/releases/download/${{ inputs.archetect-version }}/archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}.tar.gz" 2>/dev/null
        tar -xvzf ./archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}.tar.gz
        mv ./archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}/archetect .
        popd
      shell: bash
    - id: archetect-render
      run: |
        set -x
        ls -al ${{ runner.temp }}
        echo "Rendering... [Source: ${{ inputs.source }}, Destination: ${{ inputs.destination }}, Options: ${{ inputs.options }}]"
        ${{ runner.temp }}/archetect render ${{ inputs.source }} --verbose ${{ inputs.options }} -- ${{ inputs.destination }}
      shell: bash
