name: "Archetect Render Action"
description: "GitHub Action to render using Archetect https://github.com/archetect/archetect"
branding:
  icon: "activity"
  color: "blue"
inputs:
  archetect-version:
    description: The Archetect version (https://github.com/archetect/archetect/releases)
    required: false
    default: "v0.7.0"
  archetect-os:
    description: The OS for the compiled Archetect binary [linux-x64, windows-x64, osx-x64]
    required: false
    default: "linux-x64"
  source:
    description: The source directory or Git repo containing an archetype.yml
    required: true
  destination:
    description: The destination of the rendered output
    required: false
    default: "."
  options:
    description: Additional command-line options for the archetect command (e.g. -a, -A, -s)
    required: false
    default: ""
  commit:
    description: If set, changes will be committed back into the repository
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - id: install-binary
      run: |
        echo "Downloading Archetect from GitHub..."
        pushd "${{ runner.temp }}"
        curl -LO "https://github.com/archetect/archetect/releases/download/${{ inputs.archetect-version }}/archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}.tar.gz" 2>/dev/null
        tar -xvzf ./archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}.tar.gz
        mv ./archetect_${{ inputs.archetect-version }}_${{ inputs.archetect-os }}/archetect .
        popd
      shell: bash
    - id: archetect-render
      run: |
        echo "Rendering... [Source: ${{ inputs.source }}, Destination: ${{ inputs.destination }}, Options: ${{ inputs.options }}]"
        ${{ runner.temp }}/archetect render ${{ inputs.source }} --verbose ${{ inputs.options }} -- ${{ inputs.destination }}
      shell: bash
    - id: commit
      run: |
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        if [ "${{ inputs.commit }}" = "true" ]; then git add . && git commit -m "Initial commit" -m "Template Rendering from source: ${{ inputs.source }}" && git push; else echo "Skipping commit"; fi
      shell: bash
